= Constitution - AATO (Aturan-Aturan Tambahan Organisasi)
:navtitle: Bluebook - Constitution - Aturan-Aturan Tambahan Organisasi
:description: Aturan-Aturan Tambahan Organisasi COCONUT Computer Club
:keywords: COCONUT, Konstitusi, Aturan-Aturan Tambahan Organisasi

=== Bab 1 : Sanksi

==== Pasal 1 Jenis - Jenis Sanksi

Adapun jenis-jenis sanksi sebagai berikut :

.. Peringatan dan atau teguran
.. Karantina di Sekretariat
.. Resuffle
.. Pemecatan

==== Pasal 2 Alasan Pemberian Sanksi

Adapun alasan pemberian sanksi sebagai berikut :

. Tidak mematuhi Anggaran Dasar, Anggaran Rumah Tangga, serta peraturan organisasi yang berlaku di COCONUT.
. Mencemarkan nama baik organisasi.
. Tidak membayar iuran yang telah diwajibkan.
. Tidak memberikan keterangan yang dapat dipertanggung jawabkan apabila tidak menghadiri kegiatan resmi COCONUT.

==== Pasal 3 Mekanisme Pemberian Sanksi

. Apabila Sanksi atau teguran dan atau teguran mas I dan II diberikan oleh BPH atas persetujuan DPO.
. Apabila Sanksi peringatan di sekretariat atau teguran selama 2 kali masih dielakkan maka sanksi dilanjutkan ke karantina disekretariat.
. Apabila Sanksi karantina di sekretariat selama waktu yang ditentukan dan dalam tataran pengurus masih dielakkan maka sanksi dilanjutkan ke resuffle.
. Apabila Sanksi karantina disekretariat selama waktu yang ditentukan dan dalam tataran anggota masih dielakkan maka sanksi dilanjutkan ke pemberian Sanksi III (pemecatan).
. Apabila Sanksi reshuffle, masih dielakkan maka sanksi dilanjutkan ke Pemberian Sanksi III (pemecatan).
. Pemberian Sanksi III (pemecetan) diberikan oleh BPH atas Persetujuan oleh DPO dan Badan Pendiri.

=== Bab 2 : Pembelaan

==== Pasal 4 

Anggota yang diduga melakukan pelanggaran akan dibela oleh tim yang dipilih oleh praduga tersebut.

==== Pasal 5 Mekanisme Pembelaan

Mekanisme pembelaan sebagai berikut:

.. Menyelesaikan masalah yang dipradugakan pada forum khusus untuk itu.
.. Apabila point A masih dielakkan maka untuk anggota dilanjutkan ke rapat anggota dan untuk BPH dilanjutkan ke Musyawarah Besar atau Musyawarah Besar Luar Biasa.
.. Forum khusus pada point A untuk pengurus dilakukan oleh anggota atas sepengetahuan DPO, dan untuk anggota dilakukan oleh BPH.

==== Pasal 6 Sanksi DPO

Jika DPO melakukan kesalahan maka akan diadakan resuffle oleh BPH atas pertimbangan badan pendiri.

=== Bab 3 : Atribut Organisasi

==== Pasal 7

Logo COCONUT merupakan logo yang dipakai sejak periode XII sampai batas waktu yang tidak ditentukan.

==== Pasal 8 Pakaian Dinas Harian

.. Pakaian Dinas Harian (PDH) hanya digunakan pada saat aktivitas keorganisasian.
.. Pakaian Dinas Harian (PDH) dikenakan oleh anggota aktif.

==== Pasal 9 Pakaian Dinas Lapangan

.. Pakaian Dinas Lapangan (PDL) hanya digunakan pada saat aktivitas keorganisasian.
.. Pakaian Dinas Lapangan (PDL) dikenakan oleh Anggota Luar Biasa, Badan Pendiri dan Badan Pengawas

==== Pasal 10 

Bendera hanya digunakan pada aktifitas simbolis organisasi.

=== Bab 4 : Rekomendasi Musyawarah Besar

==== Pasal 11

. Badan pengurus harian memutuskan jangka waktu kepengurusan pada saat Raker.
. Badan pengurus harian wajib mensosialisasikan konstitusi secara utuh kepada seluruh anggota COCONUT.
. Membuat format pengkaderan dan kurikulum pembelajaran di COCONUT.
. Mengelola dengan baik website dan sosial media organisasi.

=== Bab 5 : Hari Peringatan

==== Pasal 12 

Tanggal 1 April setiap tahunnya di tetapkan sebagai milad COCONUT dan dirangkaikan dengan hari berkabung.

=== Bab 6 : Sanksi Musyawarah Besar

==== Pasal 13

Badan Pengurus Harian (BPH) yang tidak mengikuti keseluruhan rangkaian kegiatan Musyawarah besar (MUBES) tidak diperkenankan mengikuti prosesi pelantikan anggota baru pada periode yang sedang berjalan.
