= Constitution - PKO (Pedoman Kerja Organisasi)
:navtitle: Bluebook - Constitution - Pedoman Kerja Organisasi
:description: Pedoman Kerja Organisasi COCONUT Computer Club
:keywords: COCONUT, Konstitusi, Pedoman Kerja Organisasi


===== Bahwa Computer Club Oriented Network, Utility and Technology sebagai organisasi independen Mahasiswa yang memiliki fungsi sebagai wadah penyalur aspirasi dan kreatifitas Mahasiswa, Bertekad mencapai tujuan COCONUT yang termaktub pada Anggaran Dasar yang berbunyi “COCONUT berusaha :

. Mengarahkan Mahasiswa untuk berperan aktif dalam mewujudkan tujuan nasional melalui Tri Dharma perguruan tinggi dan sumpah mahasiswa.
. Membina dan mengembangkan kualitas serta mengupayakan kesejahteraan anggota COCONUT.
. Merencanakan dan melaksanakan kegiatan dalam bidang penalaran dan keilmuan yang berkaitan dengan spesialisasi IT.
. Usaha-usaha lain yang menunjang tujuan organisasi secara nyata dan bertanggung jawab.

Rumusan tersebut bermakna citra manusia ideal yang dikehendaki mahasiswa COCONUT, yakni manusia yang bertaqwa kepada Tuhan Yang Maha Esa, menjunjung tinggi Tri Dharma Perguruan Tinggi dan Sumpah Mahasiswa. Untuk itu COCONUT sebagai Organisasi berupaya mengembangkan potensi keanggotaan yang dimiliki. Dalam kaitan inilah, untuk memperkokoh tatanan organisasi beserta anggota diperlukan rasa memiliki dan rasa tanggung jawab dari seluruh anggota dengan memperhatikan langkah -langkah sebagai berikut :

. Mengembangkan kualitas dan kesadaran anggota terutama pengurus untuk meningkatkan rasa tanggung jawab sebagai manifestasi amanah baik terhadap organisasi maupun kepada Tuhan Yang Maha Esa.
. Keberadaan COCONUT , selain ditunjang rasa tanggung jawab dan kesadaran berorganisasi, juga dituntut rasa memiliki yang harus ditaati dan hendaknya mengarah kepada pengabdian kepada masyarakat.
. Untuk itu Anggaran Dasar dan Anggaran Rumah Tangga sebagai konstitusi organisasi serta ketentuan lainnya harus ditaati oleh seluruh anggota demi mencapai tujuan COCONUT.
. Berusaha menciptakan kondisi intelektual dengan suasana dialogis untuk memacu diri dalam pengembagan program kerja COCONUT.
